#!/usr/bin/env bash

git clone --bare git@github.com:wallforfry/dotfiles.git $HOME/.dotfiles

# define config alias locally since the dotfiles
# aren't installed on the system yet
function dotfiles {
   git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}

dotfiles checkout

if [ $? = 0 ]; then
  echo "Checked out dotfiles from git@github.com:wallforfry/dotfiles.git";
  else
    # create a directory to backup existing dotfiles to
    mkdir -p .dotfiles-backup
    echo "Moving existing dotfiles to ~/.dotfiles-backup";
    dotfiles checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .dotfiles-backup/{}
fi

# checkout dotfiles from repo
dotfiles checkout -f

dotfiles submodule update --init --recursive

dotfiles config status.showUntrackedFiles no

dotfiles config user.name Wallerand Delevacq && dotfiles config user.email wallforfry@gmail.com

echo "Installation completed, restart your shell"
